# Taps
tap "blacktop/tap"
tap "deskflow/tap"
tap "LizardByte/homebrew"

brew "syncthing"
cask "hiddenbar"
cask "deskflow"

## Shell & Core
brew "zsh"
brew "bash"
brew "micro"
brew "vim"
brew "neovim"
brew "nano"
brew "emacs"
brew "ed"
cask "claude-code"
brew "lazygit"
brew "glow"

## System Utilities
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "grep"
brew "gawk"
brew "make"
brew "cmake"
brew "binutils"
brew "wget"
brew "curl"
brew "rsync"
brew "openssh"
brew "tree"
brew "less"
brew "pv"
brew "xz"
brew "gzip"
brew "unzip"
brew "unar"
brew "readline"
brew "openssl"
brew "openssl@3"

## File Management
brew "yazi"
brew "ranger"
brew "broot"
brew "lf"
brew "fd"
brew "fzf"
brew "ack"
brew "ag"
brew "rg"
brew "ripgrep-all"

## Modern Replacements
brew "lsd"
brew "bat"
brew "eza"
brew "dust"
brew "duf"
brew "procs"
brew "sd"
brew "hyperfine"
brew "choose"
brew "fdupes"

## Diff & Comparison
brew "diffutils"
brew "colordiff"
brew "diff-so-fancy"
brew "icdiff"
brew "wdiff"

## Development Tools
brew "git"
brew "gh"
brew "lazygit"
brew "git-extras"
brew "git-flow"
brew "git-lfs"
brew "bfg"
brew "hub"
brew "pre-commit"
brew "shellcheck"
brew "yamllint"
brew "cloc"
brew "tokei"
brew "gource"
brew "ansible"
brew "ansible-lint"

## Languages & Version Managers
brew "rust"
brew "go"
brew "python3"
brew "python@3.14"
brew "pipx"
brew "uv"
brew "pyenv"
brew "node"
brew "nvm"
brew "npm"
brew "yarn"
brew "ruby"
brew "rbenv"
brew "ruby-build"
brew "composer"
brew "php-cs-fixer"
brew "phpunit"

## Build Dependencies
brew "autoconf"
brew "automake"
brew "gmp"
brew "libffi"
brew "libyaml"
brew "zlib"
brew "libevent"
brew "libpq"
brew "fontconfig"
brew "icu4c"

## Databases
brew "postgresql"
brew "mariadb"
brew "redis"

## Network Tools
brew "doggo"
brew "dnsmasq"
brew "nmap"
brew "wireshark"
brew "wireguard-tools"
brew "openconnect"
brew "mtr"
brew "fping"
brew "prettyping"
brew "httpie"
brew "wrk"
brew "iperf3"
brew "aria2"
brew "speedtest-cli"
brew "bandwhich"
brew "ngrep"
brew "iftop"
brew "ipcalc"
brew "arp-scan"
brew "telnet"
brew "autossh"
brew "mosh"
brew "parallel"

## Monitoring & System
brew "htop"
brew "btop"
brew "ctop"
brew "glances"
brew "asitop"
brew "fastfetch"
brew "fswatch"
brew "watch"
brew "tmux"
brew "screen"
brew "byobu"
brew "expect"
brew "starship"

## Terminal Multiplexers & Tools
brew "tealdeer"
brew "howdoi"
brew "thefuck"
brew "translate-shell"
brew "grc"

## File Processors
brew "exiftool"
brew "jq"
brew "yq"
brew "dasel"
brew "miller"
brew "xsv"
brew "qsv"

## Media Processing
brew "ffmpeg"
brew "mpv"
brew "mplayer"
brew "imagemagick"
brew "graphicsmagick"
brew "webp"
brew "gifski"
brew "bazarr"
brew "navidrome"

## Cloud & Deploy
brew "awscli"
brew "heroku"
brew "flyctl"
brew "vercel-cli"
brew "netlify-cli"
brew "rclone"

## Security Tools
brew "gnupg"
brew "pinentry-mac"
brew "pass"
brew "gopass"
brew "gnutls"
brew "hashcat"
brew "john"
brew "hydra"
brew "bettercap"
brew "sslsplit"
brew "fcrackzip"
brew "binwalk"
brew "md5deep"
brew "chkrootkit"
brew "spoof-mac"
brew "nikto"
brew "ncdu"

## IRC & Email
brew "irssi"
brew "bitlbee"
brew "neomutt"
brew "isync"
brew "msmtp"
brew "notmuch"
brew "urlscan"
brew "urlview"

## Window Management & macOS Specific
brew "duti"
brew "mas"
brew "wifi-password"
brew "tidy-html5"
brew "reattach-to-user-namespace"

## Misc Utilities
brew "pwgen"
brew "gpatch"
brew "m4"
brew "meson"
brew "nginx"
brew "unbound"
brew "dhcpdump"
brew "todo-txt"
brew "autojump"
brew "z"

brew "sunshine"
cask "zerotier-one"

## macOS Casks - Development
cask "kitty"
cask "iterm2"
cask "hammerspoon"
cask "github"
cask "visual-studio-code"
cask "sublime-text"
cask "phpstorm"
cask "webstorm"
cask "google-chrome"
cask "firefox"
cask "brave-browser"
cask "chromedriver"
## Docker (CLI-only, no Desktop)
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "colima"
cask "postman"
cask "ngrok"
cask "fork"

## macOS Casks - Productivity
cask "obsidian"
cask "scrivener"
cask "timing"
cask "hazel"
cask "maccy"
cask "maestral"
cask "netnewswire"
cask "numi"
cask "typora"
cask "zettlr"

## macOS Casks - Security
cask "bitwarden"
cask "arq"
cask "little-snitch"
cask "knockknock"
cask "onyx"
cask "oversight"

## macOS Casks - Utilities
cask "keka"
cask "dupeguru"
cask "cyberduck"
cask "dbvisualizer"
cask "dbeaver-community"
cask "sequel-ace"
cask "postico"
cask "mysqlworkbench"
cask "db-browser-for-sqlite"
cask "sdformatter"
cask "balenaetcher"
cask "unetbootin"
cask "transmission"
cask "vlc"
cask "iina"
cask "audio-hijack"
cask "xquartz"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "macfuse"
cask "fujitsu-scansnap-home"
cask "superduper"
cask "tabula"
cask "utm"
cask "microsoft-remote-desktop"
cask "vnc-viewer"
cask "transmit"
cask "cryptomator"
cask "keybase"
cask "qtpass"
cask "macs-fan-control"
cask "appcleaner"
cask "ccleaner"
cask "flux-app"
cask "disk-inventory-x"
cask "amethyst"
cask "diffmerge"
cask "meld"
cask "lepton"

## macOS Casks - Communication
cask "element"
cask "discord"
cask "telegram"
cask "signal"
cask "rocket-chat"
cask "volt-app"
cask "podcastmenu"

## macOS Casks - Media & Entertainment
cask "spotify"
cask "tidal"
cask "ytmdesktop-youtube-music"
cask "plex"
cask "plex-media-server"
cask "kodi"
cask "jellyfin-media-player"
cask "handbrake-app"
cask "makemkv"
cask "sabnzbd"
cask "sonarr"
cask "radarr"
cask "lidarr"
cask "prowlarr"
cask "embyserver"
cask "jellyfin"
cask "retroarch"
cask "openemu"
cask "dolphin"
cask "pcsx2"
cask "cemu"
cask "steam"
cask "epic-games"
cask "battle-net"
cask "ea"

## QuickLook Plugins
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-video"
cask "quicklook-csv"
cask "suspicious-package"
cask "webpquicklook"

## Fonts
cask "font-fontawesome"
cask "font-awesome-terminal-fonts"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-g-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-roboto-mono"
cask "font-roboto-mono-for-powerline"
cask "font-source-code-pro"
