---
- hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: true

  roles:
    - base
    - workstation
    - { role: pushtotalk, when: ansible_system == "Darwin" }
    - { role: docker, when: ansible_system == "Darwin" }
    - { role: zerotier, when: ansible_system == "Darwin" }
