---
- name: workstation | macOS | include vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: workstation | macOS | install homebrew packages
  import_tasks: software/homebrew.yml
  tags: homebrew

- name: workstation | macOS | apply system defaults
  import_tasks: system_setup/macos_defaults.yml
  when: ansible_system == "Darwin"
  tags: macos,defaults

- name: workstation | macOS | configure hammerspoon and karabiner
  import_tasks: system_setup/hammerspoon.yml
  when: ansible_system == "Darwin"
  tags: hammerspoon,karabiner
