# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  ## User configs
  - import_tasks: "users/user.yml"

  ## desktop environments (Linux only)
  - include_tasks: desktop_environments/mate/main.yml
    when:
      - mate is defined and mate == true
      - ansible_distribution != "Darwin"

  - include_tasks: desktop_environments/gnome/main.yml
    when:
      - gnome is defined and gnome == true
      - ansible_distribution != "Darwin"

  ## system setup
  # - import_tasks: system_setup/autofs.yml
  # - import_tasks: system_setup/scripts.yml
  # - import_tasks: system_setup/tweaks.yml

  ## install software
  # - import_tasks: software/packages_pacman.yml
  - import_tasks: software/browser_extensions.yml

  rescue:
    - set_fact: task_failed=true
