- name: users | create group
  tags: groups,users
  become: yes
  check_mode: no
  group:
    name: "{{ username }}"
    state: present

- name: users | create user
  tags: sudo,users
  become: yes
  user:
    name: "{{ username }}"
    group: "{{ username }}"
    groups: "{{ username }},staff,{{ sudo_group | default('admin') }}"
    state: present
    comment: "user"
    shell: /usr/bin/zsh

- name: users | add sudoers file
  tags: settings,sudo,system,users
  become: yes
  command: "rm -f /etc/sudoers.d/{{ username }}; echo '{{ username }} ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/{{ username }}"

- name: users | create .ssh directory
  tags: dotfiles,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700
  with_items:
    - { dir: "{{ userhome }}/.ssh" }

- name: users | add all public keys
  tags: dotfiles,ssh,ssh-keys,users
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "users/{{ username }}/ssh/*.pub"

- name: Dotfiles - Get home directory
  user:
    name: "{{ username }}"
    state: present
  register: dotfiles_user_registered
  check_mode: no
  tags: dotfiles,users,barerepo

- name: Dotfiles - Set checkout if undefined
  set_fact:
    dotfiles_checkout: ['/*']
  when: dotfiles_checkout is undefined
  tags: dotfiles,users,barerepo

- name: Dotfiles - Check if directory exists
  stat:
    path: "{{ repo_dir }}"
  register: repo_directory
  check_mode: no
  tags: dotfiles,users,barerepo

- name: Git | Ensure bare repo is checked out
  become_user: "{{ username }}"
  git:
    repo: "{{ upstream }}"
    dest: "{{ repo_dir }}"
    version: "master"
    bare: yes
    track_submodules: yes
    recursive: yes
  when: not repo_directory.stat.exists
  tags: dotfiles,users,barerepo

- name: Git | Overwrite distro default dotfiles on the first run
  become_user: "{{ username }}"
  command: "git reset --hard"
  when: not repo_directory.stat.exists
  tags: dotfiles,users,barerepo

- name: Dotfiles - Unset bare option to prevent fatal error (must be run in a work tree)
  command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} config --local core.bare false"
  become: yes
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

- name: Dotfiles - Enable sparse checkout
  command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} config --local core.sparseCheckout true"
  become: yes
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

- name: Dotfiles - Disable showing untracked files
  command: "git --git-dir={{ repo_dir }} --work-tree={{ work_dir }} config --local status.showUntrackedFiles no"
  become: yes
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

- name: Git | Create symbolic link
  file:
    src: "{{ repo_dir }}"
    dest: "{{ work_dir }}.git"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  become_user: "{{ username }}"
  tags: dotfiles,users,barerepo

- name: users | copy config directory
  copy:
    src: "{{ item }}"
    dest: "{{ userhome }}/.config/git/"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    ["users/{{ username }}/config/git/.gitconfig-personal", "users/{{ username }}/config/git/.gitconfig-hero", "users/{{ username }}/config/git/.gitconfig-company" ]

- name: users | copy config directory pass
  copy:
    src: "{{ item }}"
    dest: "{{ userhome }}/.config/pass-git-helper/"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    ["users/{{ username }}/config/pass-git-helper/git-pass-mapping.ini" ]

- name: Dotfiles - Clone z-zsh
  stat:
    path: "{{ userhome }}/z-zsh"
  register: subrepo_directory
  check_mode: no
  tags: dotfiles,users,submodules
- name: Git | Checkout z-zsh repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/sjl/z-zsh.git"
    dest: "{{ userhome }}/z-zsh"
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone .vim
  stat:
    path: "{{ userhome }}/.vim"
  register: subrepo_directory
  check_mode: no
  tags: dotfiles,users,submodules
- name: Git | Checkout .vim repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/homeofficehost/.vim.git"
    dest: "{{ userhome }}/.vim"
    update: yes
    track_submodules: yes
    recursive: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone setup-keys
  stat:
    path: "{{ userhome }}/setup-keys"
  register: subrepo_directory
  check_mode: no
  tags: dotfiles,users,submodules
- name: Git | Checkout setup-keys repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/homeofficehost/setup-keys.git"
    dest: "{{ userhome }}/setup-keys"
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone .oh-my-zsh
  stat:
    path: "{{ userhome }}/.oh-my-zsh"
  register: subrepo_directory
  check_mode: no
  tags: dotfiles,users,submodules
- name: Git | Checkout .oh-my-zsh repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ userhome }}/.oh-my-zsh"
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone .oh-my-zsh-custom
  stat:
    path: "{{ userhome }}/.oh-my-zsh-custom"
  register: subrepo_directory
  check_mode: no
  tags: dotfiles,users,submodules
- name: Git | Checkout .oh-my-zsh-custom repository
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/homeofficehost/oh-my-zsh-custom.git"
    dest: "{{ userhome }}/.oh-my-zsh-custom"
    update: yes
    track_submodules: yes
    recursive: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles - Clone personal site
  stat:
    path: "{{ userhome }}/site"
  register: subrepo_directory
  check_mode: no
  tags: dotfiles,users,submodules
- name: Git | Clone personal
  become_user: "{{ username }}"
  git:
    repo: "{{ site_upstream | default('https://github.com/homeofficehost/homeofficehost.github.io') }}"
    dest: "{{ userhome }}/site"
    update: yes
    track_submodules: yes
    recursive: yes
  when: not subrepo_directory.stat.exists
  tags: dotfiles,users,submodules

- name: Dotfiles | Check if dotfiles bare repo exists
  stat:
    path: "{{ userhome }}/.dotfiles-bare"
  register: dotfiles_bare_directory
  check_mode: no
  tags: dotfiles,users,personal

- name: Dotfiles | Clone dotfiles repository as bare repo
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ userhome }}/.dotfiles-bare"
    version: "main"
    bare: yes
    recursive: yes
  when: not dotfiles_bare_directory.stat.exists
  tags: dotfiles,users,personal

- name: Dotfiles | Configure bare repo
  become_user: "{{ username }}"
  command: "git --git-dir={{ userhome }}/.dotfiles-bare config core.bare true"
  when: not dotfiles_bare_directory.stat.exists
  tags: dotfiles,users,personal

- name: Dotfiles | Checkout dotfiles files to home
  become_user: "{{ username }}"
  command: "git --git-dir={{ userhome }}/.dotfiles-bare --work-tree={{ userhome }} checkout"
  when: not dotfiles_bare_directory.stat.exists
  tags: dotfiles,users,personal

- name: Dotfiles | Set hide untracked files
  become_user: "{{ username }}"
  command: "git --git-dir={{ userhome }}/.dotfiles-bare --work-tree={{ userhome }} config status.showUntrackedFiles no"
  when: not dotfiles_bare_directory.stat.exists
  tags: dotfiles,users,personal

- name: Dotfiles | Mark provision as changed
  set_fact:
    provision_changed: true
  when: not dotfiles_bare_directory.stat.exists
  tags: dotfiles,users,personal
