---
- name: system setup | hammerspoon | ensure hammerspoon config directory exists
  file:
    path: "{{ userhome }}/.hammerspoon"
    state: directory
    mode: "0755"

- name: system setup | hammerspoon | install init.lua
  copy:
    src: hammerspoon/init.lua
    dest: "{{ userhome }}/.hammerspoon/init.lua"
    mode: "0644"
  register: hammerspoon_config

- name: system setup | hammerspoon | ensure hammerspoon is running
  command: open -a Hammerspoon
  changed_when: false

- name: system setup | hammerspoon | reload config
  command: hs -c "hs.reload()"
  changed_when: false
  when: hammerspoon_config.changed
  ignore_errors: true
