---
- name: zerotier | install via homebrew
  homebrew_cask:
    name: zerotier-one
    state: present
  tags: zerotier

- name: zerotier | start service
  command: sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
  ignore_errors: true
  changed_when: true
  tags: zerotier

- name: zerotier | join network
  command: sudo /Library/Application\ Support/ZeroTier/One/zerotier-cli join 8286ac0e47808030
  ignore_errors: true
  changed_when: true
  tags: zerotier
