---
- name: zerotier | check if installed
  command: brew list --cask zerotier-one
  register: zerotier_installed
  failed_when: false
  changed_when: false
  tags: zerotier

- name: zerotier | install via homebrew
  command: brew install --cask zerotier-one
  when: zerotier_installed.rc != 0
  tags: zerotier

- name: zerotier | start service
  command: sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
  ignore_errors: true
  changed_when: true
  tags: zerotier

- name: zerotier | join network
  command: sudo /Library/Application\ Support/ZeroTier/One/zerotier-cli join 8286ac0e47808030
  ignore_errors: true
  changed_when: true
  tags: zerotier
