---
- name: workstation | homebrew | install packages from Brewfile
  tags: homebrew
  command: brew bundle install --file={{ playbook_dir }}/Brewfile
  register: brew_bundle_result
  changed_when: "'Installing' in brew_bundle_result.stdout"

- name: workstation | homebrew | set changed flag
  set_fact:
    provision_changed: true
  when: brew_bundle_result is defined and brew_bundle_result.changed | bool

- name: workstation | apps | remove blacklisted macOS apps
  become: yes
  tags: apps
  shell: |
    changed=0
    for app in $(grep -v '^#' {{ playbook_dir }}/Blacklistfile | grep -v '^$'); do
      [ -d "/Applications/${app}.app" ] && rm -rf "/Applications/${app}.app" && changed=1
    done
    exit $changed
  register: blacklist_result
  failed_when: blacklist_result.rc > 1
  changed_when: blacklist_result.rc | int == 1

- name: workstation | apps | set changed flag
  set_fact:
    provision_changed: true
  when: blacklist_result is defined and blacklist_result.changed | bool

