---
- name: ansible setup | ensure ansible is installed
  tags: ansible,ansible-setup
  homebrew:
    name: ansible
    state: present

- name: ansible setup | generate provision script from template
  tags: ansible,ansible-setup,scripts
  template:
    src: provision.sh.j2
    dest: /usr/local/bin/provision
    owner: root
    group: wheel
    mode: 0755
