---
- name: base | macOS | include vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: base | macOS | setup ansible
  import_tasks: ansible_setup.yml

- name: base | macOS | setup cron
  import_tasks: system_setup/cron.yml
