# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

# Linux-only tasks
- block:

  - import_tasks: "users/user.yml"

  - import_tasks: users/ssh_github.yml

  - import_tasks: ansible_setup.yml

  rescue:
    - set_fact: task_failed=true

  when: ansible_os_family != "Darwin"

# Cron - runs on both Linux and macOS
- import_tasks: system_setup/cron.yml
