---
- name: system setup | cron | schedule automatic ansible provisioning
  tags: cron
  cron:
    name: "ansible provision"
    user: "{{ username }}"
    hour: "{{ ansible_cron_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: "{ date; /usr/local/bin/provision; RC=$?; date; echo \"Exit code: $RC\"; } >> /Users/{{ username }}/ansible_provision.log 2>&1 && if [ $RC -eq 0 ]; then echo $(date) > /Users/{{ username }}/ansible_provision_last_run.txt; fi"

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  cron:
    name: "ansible refresh at boot"
    user: "{{ username }}"
    special_time: reboot
    job: "/bin/rm -rf /Users/{{ username }}/.ansible ~/.ansible"
