---
- name: system setup | sudo | enable passwordless sudo for user
  tags: sudo
  copy:
    content: "{{ username }} ALL=(ALL) NOPASSWD: ALL\n"
    dest: "/etc/sudoers.d/{{ username }}"
    owner: root
    group: wheel
    mode: '0440'
    validate: "visudo -cf %s"
  become: yes
  when: enable_passwordless_sudo | default(false)

- name: system setup | sudo | remove legacy sudoers entry
  tags: sudo
  lineinfile:
    path: /etc/sudoers
    regexp: "^{{ username }}\\s+ALL=\\(ALL\\)\\s+NOPASSWD:\\s+ALL\\s*$"
    state: absent
    validate: "visudo -cf %s"
  become: yes

- name: system setup | sudo | disable passwordless sudo for user
  tags: sudo
  file:
    path: "/etc/sudoers.d/{{ username }}"
    state: absent
  become: yes
  when: not (enable_passwordless_sudo | default(false))
